apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: example
spec:
  privileged: true # Don't allow privileged pods!
  # The rest fills in some required fields.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhcnRpZmFjdHMubXNhcC5pbyI6eyJhdXRoIjoiY205aWIzUWtZM0JrWlhZNlpYbEthR0pIWTJsUGFVcFRWWHBKTVU1cFNYTkpibEkxWTBOSk5rbHJjRmhXUTBvNUxtVjVTbXhsU0VGcFQycEZNazFVVVhoUFZFMHlUbnBOYzBsdGJHaGtRMGsyVFZSVk5FMXFXVEZPZWxrelRYbDNhV0ZZVG5wSmFtOXBZVWRHZVZsdE9YbE1XRkoyWVRKV2RVeFhVbXhhYlVZeFlraFNTbU16VGpGYVdFbHBURU5LY0ZwRFNUWk5lbEV3VFVSbmQweERTbmRoVjFGcFQycFJjMGx0Um1wWk1sWjZZM2xKTmxjemMybFZiVlo2WWpOV2VWa3lWV2xQYVVsMlkwaEtkbUZ0Vm1wa1F6Z3dURE5LYkdOSE9YcGhXRkoyWTI1cmFVeERTa0paTTFKd1lqSTBhVTlwU25ka1YzaHpTV2wzYVZKWFdtMWFWMDR3U1dwdmFVbHVNV1JtVVM1VmFXVlpiREF4Vm5wTlUzaHZXRlJKU2t0dGFEaGxTSGhRYm5SdVVIUkVhRUZGZWxWWk1EQjRTMUJSVm5kaFNIVTFTa3N6VDIweGQxbGpTMHRhVTFsRmRrRnhXR2RxTTNOV05tRlNWa1l3UXpKTVFXb3pZa2MzZFVKdVYyUmxZblZ0VXpSQmN5MXZMV2R3UWxCbFV6SnNlVFEwTkVaVmRrOTJOVkZuWkdjNFlWZ3pVM1p4YzJ0SFVWVXpiRWwyU1RGWmQzVnNjelZhYlUxMWMyczNkVll5YldsRlNtOW1kVmg1TFMwdE4wcHlhbE4yWmxsUGJURlBVSGRtYzJaTFFuUlNZbTVoZVRodllWcE5lbmc1YW5seU5FOTFVMnd4V0daTGVUQjNkV001VFVoRmVtUklSWGRvVERsdWJEVkxZVlZ3YTFsNGIwdDBRVVJvUWtRek0zRm1ZMUpTVVc4elVWTTFkamd6WmxneWJqaHpRWFZpVmtkTE5GSkJSVkZPVTBWc1VIVmtXRGhoVkVObFJXb3hTRGMzYlRodlIyeEthamhhUmxwaGNYRmFaMjg1WmxWZmRuSTVUVFZ6YnpORFEyZDFaRVphTUZFPSIsInBhc3N3b3JkIjoiZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmxlSEFpT2pFMk1UUXhPVE0yTnpNc0ltbGhkQ0k2TVRVNE1qWTFOelkzTXl3aWFYTnpJam9pYUdGeVltOXlMWFJ2YTJWdUxXUmxabUYxYkhSSmMzTjFaWElpTENKcFpDSTZNelEwTURnd0xDSndhV1FpT2pRc0ltRmpZMlZ6Y3lJNlczc2lVbVZ6YjNWeVkyVWlPaUl2Y0hKdmFtVmpkQzgwTDNKbGNHOXphWFJ2Y25raUxDSkJZM1JwYjI0aU9pSndkV3hzSWl3aVJXWm1aV04wSWpvaUluMWRmUS5VaWVZbDAxVnpNU3hvWFRJSkttaDhlSHhQbnRuUHREaEFFelVZMDB4S1BRVndhSHU1SkszT20xd1ljS0taU1lFdkFxWGdqM3NWNmFSVkYwQzJMQWozYkc3dUJuV2RlYnVtUzRBcy1vLWdwQlBlUzJseTQ0NEZVdk92NVFnZGc4YVgzU3Zxc2tHUVUzbEl2STFZd3VsczVabU11c2s3dVYybWlFSm9mdVh5LS0tN0pyalN2ZllPbTFPUHdmc2ZLQnRSYm5heThvYVpNeng5anlyNE91U2wxWGZLeTB3dWM5TUhFemRIRXdoTDlubDVLYVVwa1l4b0t0QURoQkQzM3FmY1JSUW8zUVM1djgzZlgybjhzQXViVkdLNFJBRVFOU0VsUHVkWDhhVENlRWoxSDc3bThvR2xKajhaRlphcXFaZ285ZlVfdnI5TTVzbzNDQ2d1ZEZaMFEiLCJ1c2VybmFtZSI6InJvYm90JGNwZGV2In19fQ==
kind: Secret
metadata:
  name: devdocker-registrykey
  namespace: load-test
type: kubernetes.io/dockerconfigjson
