apiVersion: batch/v1
kind: Job
metadata:
  name: foo-job-sleep-10-{{ randAlphaNum 5 | lower}}
spec:
  backoffLimit: 0
  template:
    spec:
      backoffLimit: 0
      restartPolicy: Never
      imagePullSecrets:
      - name: devdocker-registrykey
      restartPolicy: Never
      containers:
      - name: foo-job
        image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
        command: ["sleep", "10"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: foo-job-sleep-false-{{ randAlphaNum 5 | lower}}
spec:
  backoffLimit: 0
  template:
    spec:
      backoffLimit: 0
      restartPolicy: Never
      imagePullSecrets:
      - name: devdocker-registrykey
      restartPolicy: Never
      containers:
      - name: foo-job
        image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
        command: ["bash", "-c", "sleep 10 && false"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: foo-job-sleep-asdf-{{ randAlphaNum 5 | lower}}
spec:
  backoffLimit: 0
  template:
    spec:
      backoffLimit: 0
      restartPolicy: Never
      imagePullSecrets:
      - name: devdocker-registrykey
      restartPolicy: Never
      containers:
      - name: foo-job
        image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
        command: ["bash", "-c", "sleep 10 && asdf"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: foo-job-asdf-{{ randAlphaNum 5 | lower}}
spec:
  backoffLimit: 0
  template:
    spec:
      backoffLimit: 0
      restartPolicy: Never
      imagePullSecrets:
      - name: devdocker-registrykey
      restartPolicy: Never
      containers:
      - name: foo-job
        image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
        command: ["asdf"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: foo-job-true-{{ randAlphaNum 5 | lower}}
spec:
  backoffLimit: 0
  template:
    spec:
      backoffLimit: 0
      restartPolicy: Never
      imagePullSecrets:
      - name: devdocker-registrykey
      restartPolicy: Never
      containers:
      - name: foo-job
        image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
        command: ["true"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: foo-job-false-{{ randAlphaNum 5 | lower}}
spec:
  backoffLimit: 0
  template:
    spec:
      backoffLimit: 0
      restartPolicy: Never
      imagePullSecrets:
      - name: devdocker-registrykey
      restartPolicy: Never
      containers:
      - name: foo-job
        image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
        command: ["false"]
---
apiVersion: v1
kind: Pod
metadata:
  name: foo-pod-sleep-10-{{ randAlphaNum 5 | lower}}
  annotations:
    "helm.sh/hook": test-success
spec:
  restartPolicy: Never
  imagePullSecrets:
  - name: devdocker-registrykey
  restartPolicy: Never
  containers:
  - name: foo-pod
    image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
    command: ["sleep", "10"]
---
apiVersion: v1
kind: Pod
metadata:
  name: foo-pod-sleep-false-{{ randAlphaNum 5 | lower}}
  annotations:
    "helm.sh/hook": test-success
spec:
  restartPolicy: Never
  imagePullSecrets:
  - name: devdocker-registrykey
  restartPolicy: Never
  containers:
  - name: foo-pod
    image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
    command: ["bash", "-c", "sleep 10 && false"]
---
apiVersion: v1
kind: Pod
metadata:
  name: foo-pod-sleep-asdf-{{ randAlphaNum 5 | lower}}
  annotations:
    "helm.sh/hook": test-success
spec:
  restartPolicy: Never
  imagePullSecrets:
  - name: devdocker-registrykey
  restartPolicy: Never
  containers:
  - name: foo-pod
    image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
    command: ["bash", "-c", "sleep 10 && asdf"]
---
apiVersion: v1
kind: Pod
metadata:
  name: foo-pod-asdf-{{ randAlphaNum 5 | lower}}
  annotations:
    "helm.sh/hook": test-success
spec:
  restartPolicy: Never
  imagePullSecrets:
  - name: devdocker-registrykey
  restartPolicy: Never
  containers:
  - name: foo-pod
    image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
    command: ["asdf"]
---
apiVersion: v1
kind: Pod
metadata:
  name: foo-pod-true-{{ randAlphaNum 5 | lower}}
  annotations:
    "helm.sh/hook": test-success
spec:
  restartPolicy: Never
  imagePullSecrets:
  - name: devdocker-registrykey
  restartPolicy: Never
  containers:
  - name: foo-pod
    image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
    command: ["true"]
---
apiVersion: v1
kind: Pod
metadata:
  name: foo-pod-false-{{ randAlphaNum 5 | lower}}
  annotations:
    "helm.sh/hook": test-success
spec:
  restartPolicy: Never
  imagePullSecrets:
  - name: devdocker-registrykey
  restartPolicy: Never
  containers:
  - name: foo-pod
    image: artifacts.msap.io/mulesoft/core-paas-istio-kubectl:latest
    command: ["false"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: killer
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: istio-killer-secret
  annotations:
    kubernetes.io/service-account.name: killer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: killer-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: ServiceAccount
  name: killer
  namespace: load-test
roleRef:
  kind: ClusterRole
  name: killer-role
  apiGroup: rbac.authorization.k8s.io


