apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadbots
  template:
    metadata:
      name: loadbots
      labels:
        app: loadbots
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}aggregator{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      imagePullSecrets:
      - name: devdocker-registrykey
      containers:
      - name: loadbots
        image: endianogino/vegeta-server:{{ .Values.images.loadbotVersion }}
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: false
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - -host=webserver
        - -address=:8080
        - -rate={{ .Values.loadbot.rate }}
        - -workers={{ .Values.loadbot.workers}}
        - -duration={{ .Values.loadbot.duration}}
        ports:
        - name: http-port
          protocol: TCP
          containerPort: 8080
        resources:
          requests:
            cpu: {{ .Values.cpuRequests.loadbot }}
            memory: {{ .Values.memRequests.loadbot }}
