apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: webserver
      labels:
        app: webserver
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}aggregator{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      imagePullSecrets:
      - name: devdocker-registrykey
      containers:
      - name: webserver
        image: endianogino/simple-webserver:{{ .Values.images.webserverVersion }}
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: false
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - -port=80
        ports:
        - name: http-port
          protocol: TCP
          containerPort: 80
        resources:
          requests:
            cpu: {{ .Values.cpuRequests.webserver }}
            memory: {{ .Values.memRequests.webserver }}
