apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "base.labels.mulesoft.test" . | indent 4 | trim }}
    app: istio-demo-client
    istio: demo
  name: {{ .Values.test.client.name }}
spec:
  selector:
    matchLabels:
      app: istio-demo-client
  replicas: 1
  template:
    metadata:
      labels:
        {{ include "base.labels.mulesoft.test" . | indent 8 | trim }}
        app: istio-demo-client
        istio: demo
      name: {{ .Values.test.client.name }}
    spec:
      {{ include "base.image.pull-secret-name" . | indent 6 | trim }}
      containers:
      - name: {{ .Values.test.client.name }}
        {{- with .Values.test }}
        {{ include "base.resources.limits" . | indent 8 |trim }}
        {{- end }}
        command:
        - /bin/bash
        - -c
        - "while true; do sleep 1; curl -i -s $TARGET/cat; echo; done"
        env:
        - name: TARGET
          value: {{ .Values.test.server.name }}:80
        image: {{ .Values.test.client.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        securityContext:
          runAsUser: 2020
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "base.labels.mulesoft.test" . | indent 4 | trim }}
    app: istio-demo-server
    istio: demo
  name: {{ .Values.test.server.name }}
spec:
  selector:
    matchLabels:
      app: istio-demo-server
  replicas: 1
  template:
    metadata:
      labels:
        {{ include "base.labels.mulesoft.test" . | indent 8 | trim }}
        app: istio-demo-server
        istio: demo
      name: {{ .Values.test.client.name }}
    spec:
      {{ include "base.image.pull-secret-name" . | indent 6 | trim }}
      containers:
      - name: {{ .Values.test.server.name }}
        {{- with .Values.test }}
        {{ include "base.resources.limits" . | indent 8 |trim }}
        {{- end }}
        command: ["/bin/bash", "-c", "go run /etc/files/server.go "]
        image: {{ .Values.test.server.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 80
        volumeMounts:
          - name: files
            mountPath: /etc/files
      volumes:
        - name: files
          configMap:
            name: istio-demo-server-code
            defaultMode: 511
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    {{ include "base.labels.mulesoft.test" . | indent 4 | trim }}
    app: istio-demo-cat
    istio: demo
  name: istio-demo-cat
spec:
  selector:
    matchLabels:
      app: istio-demo-cat
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{ include "base.labels.mulesoft.test" . | indent 8| trim }}
        app: istio-demo-cat
        istio: demo
      name: {{ .Values.test.client.name }}
    spec:
      {{ include "base.image.pull-secret-name" . | indent 6 | trim }}
      containers:
      - name: istio-demo-cat
        {{- with .Values.test }}
        {{ include "base.resources.limits" . | indent 8 |trim }}
        {{- end }}
        command:
        - /bin/bash
        - -c
        - "sleep 100000"
        image: {{ .Values.test.client.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        securityContext:
          runAsUser: 2020
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.test.server.name }}
  labels:
    {{ include "base.labels.mulesoft.test" . | indent 4 | trim }}
    istio: demo
    app: istio-demo-server
spec:
  replicas: 1
  ports:
    - protocol: TCP
      port: 80
      name: http
  selector:
    istio: demo
    app: istio-demo-server
