apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-demo-server-code
  labels:
    {{ include "base.labels.mulesoft.test" . | indent 4 | trim }}
    istio: demo
data:
binaryData:
  server.go: |-
    {{ .Files.Get "server.go" | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-demo-proxy-code
  labels:
    {{ include "base.labels.mulesoft.test" . | indent 4 | trim }}
    istio: demo-proxy
data:
binaryData:
  proxy.go: |-
    {{ .Files.Get "proxy/proxy.go" | b64enc }}

  go.mod: |-
    {{ .Files.Get "proxy/go.mod" | b64enc }}

  go.sum: |-
    {{ .Files.Get "proxy/go.sum" | b64enc }}
