imagePullPolicy: IfNotPresent
images:
  loadbotVersion: "1.0"
  webserverVersion: "1.0"
  aggregatorVersion: "1.0"

cpuRequests:
  loadbot: "250m"
  webserver: "250m"

memRequests:
  loadbot: "800M"
  webserver: "800M"

rbac:
  create: true
  serviceAccountName: default

aggregator:
  maxReplicas: 100
  logLevel: 2

loadbot:
  rate: 1
  workers: 1
  duration: 10s

enabed: false
